server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: verba-proxy
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: verba-api
          uri: lb://verba-api
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

        - id: verba-data
          uri: lb://verba-data
          predicates:
            - Path=/data/*
          filters:
            - AuthenticationFilter

        - id: verba-auth
          uri: lb://verba-auth
          predicates:
            - Path=/auth/**