server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: verba-proxy
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true