before_script:
  - chmod +x gradlew

stages:
  - build
  - deploy

build:
  tags:
    - build
  stage: build
  script:
    - docker-compose kill
  only:
    - develop

deploy:
  tags:
    - deploy
  stage: deploy
  script:
    - ./gradlew bootJar
    - docker-compose up -d --force-recreate --no-deps --build
  only:
    - develop

