before_script:
  - chmod +x gradlew

stages:
  - build
  - test
  - deploy

build:
  tags:
    - build
  stage: build
  script:
    - ./gradlew bootJar
    - docker-compose build

deploy:
  tags:
    - deploy
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - develop

