stages:
  - build
  - test
  - deploy

build:
  image: ubuntu:22.04
  tags:
    - build
  stage: build
  script:
    - docker-compose build

test:
  image: ubuntu:22.04
  tags:
    - test
  stage: test
  script:
    - docker-compose run verba-api mvn test
    - docker-compose run verba-data mvn test
    - docker-compose run verba-proxy mvn test

deploy:
  image: ubuntu:22.04
  tags:
    - deploy
  stage: deploy
  script:
    - docker-compose up -d

