stages:
  - build
  - test
  - deploy

build:
  tags:
    - hello
  stage: build
  script:
    - mvn package -DskipTests
    - docker-compose build
  before_script:
    - docker-compose --version

test:
  tags:
    - hello
  stage: test
  script:
    - mvn test

deploy:
  tags:
    - hello
  stage: deploy
  script:
    - docker-compose up -d

