before_script:
  - chmod +x gradlew

stages:
  - build
  - deploy
  - test

test:
  tags:
    - test
  stage: test
  script:
    - echo "Все ок)"

build:
  tags:
    - build
  stage: build
  script:
    - docker-compose down
  only:
    - develop

deploy:
  tags:
    - deploy
  stage: deploy
  script:
    - ./gradlew bootJar
    - docker-compose up -d --force-recreate --no-deps --build
  only:
    - develop

