stages:
  - build
  - test
  - deploy

build:
  tags:
    - hello
  stage: build
  script:
    - maven clean package
  before_script:
    - docker-compose --version

test:
  tags:
    - hello
  stage: test
  script:
    - docker-compose run verba-api mvn test
    - docker-compose run verba-data mvn test
    - docker-compose run verba-proxy mvn test

deploy:
  tags:
    - hello
  stage: deploy
  script:
    - docker-compose up -d

