stages:
  - build
  - test
  - deploy

build:
  tags:
    - build
  stage: build
  script:
    - mvn package -DskipTests
    - ./verba-api/gradlew build -x test
    - docker-compose build
    
test:
  tags:
    - test
  stage: test
  script:
    - mvn test

deploy:
  tags:
    - deploy
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - merge_request
    - master
    - develop

