version: "3"
services:
  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - eureka-web
    ports:
      - "8085:8085"
    expose:
      - "8085"

  verba-api:
    container_name: verba-api
    build: ./verba-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5431/db
    networks:
      - postgres-web
      - eureka-web
    depends_on:
      - postgres

  verba-data:
    container_name: verba-data
    build: ./verba-data
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - eureka-web

  verba-proxy:
    container_name: verba-proxy
    build: ./verba-proxy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - eureka-web
    ports:
      - "8080:8080"
    expose:
      - "8080"

  postgres:
    container_name: postgres
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/db
    networks:
      - postgres-web
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always

networks:
  postgres-web:
  eureka-web:
