server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    preferIpAddress: true


spring:
  application:
    name: verba-data


api:
  openai:
    url: "https://api.openai.com/"
    content-type:  "application/json"
    api-key: "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"
  yandex:
    url: "https://dictionary.yandex.net/"
    api-key: "dict.1.1.20230429T080024Z.644ba2569c2dd56a.3410b92a287f16c4b4f37dfdce3c14dca0932283"

