server:
    port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8085/eureka}
  instance:
    preferIpAddress: true



spring:
  application:
    name: verba-data
