server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    preferIpAddress: true

#postgres
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:35432/db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  application:
    name: verba-api