server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    preferIpAddress: true
#postgres
spring:
  application:
    name: verba-api
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:55431/db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
springdoc:
  swagger-ui:
    enabled: true
    url: swagger