server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    preferIpAddress: true

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
#postgres
spring:
  application:
    name: verba-auth
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:55431/db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver